/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary": "#ac322d",
        "tertiary-fixed-dim": "#a4c9ff",
        "on-primary": "#ffffff",
        "inverse-surface": "#32302b",
        "surface-container": "#f2ede5",
        "tertiary": "#0060ac",
        "on-error": "#ffffff",
        "primary-container": "#b9a76d",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1d1c17",
        "on-surface-variant": "#4b463a",
        "on-primary-fixed-variant": "#534616",
        "surface-variant": "#e7e2da",
        "on-background": "#1d1c17",
        "on-primary-fixed": "#231b00",
        "background": "#fef9f1",
        "secondary-container": "#fe6d62",
        "on-tertiary-container": "#003e73",
        "surface-tint": "#6c5d2b",
        "on-error-container": "#93000a",
        "outline": "#7c7769",
        "primary": "#6c5d2b",
        "tertiary-fixed": "#d4e3ff",
        "on-tertiary-fixed": "#001c39",
        "on-secondary-fixed-variant": "#8b1918",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#d9c689",
        "tertiary-container": "#68abff",
        "surface-container-low": "#f8f3eb",
        "surface-dim": "#ded9d2",
        "surface-bright": "#fef9f1",
        "on-secondary-fixed": "#410002",
        "surface-container-high": "#ece8e0",
        "on-primary-container": "#483c0c",
        "primary-fixed": "#f6e1a2",
        "secondary-fixed": "#ffdad6",
        "on-secondary-container": "#6d0007",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004883",
        "outline-variant": "#cdc6b6",
        "surface-container-highest": "#e7e2da",
        "inverse-on-surface": "#f5f0e8",
        "inverse-primary": "#d9c689",
        "secondary-fixed-dim": "#ffb4ac",
        "surface": "#fef9f1",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a"
      },
      "borderRadius": {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Inter"],
        "plus-jakarta": ["Plus Jakarta Sans"],
        "be-vietnam": ["Be Vietnam Pro"]
      }
    },
  },
  plugins: [],
}
